In [ ]:
import requests
import pandas as pd

url = "https://dummyjson.com/users?limit=100"

response = requests.get(url)
data = response.json()


df = pd.json_normalize(data["users"])

df.head()

,id,firstName,lastName,maidenName,age,gender,email,phone,username,password,...,company.address.city,company.address.state,company.address.stateCode,company.address.postalCode,company.address.coordinates.lat,company.address.coordinates.lng,company.address.country,crypto.coin,crypto.wallet,crypto.network
0,1,Emily,Johnson,Smith,29,female,emily.johnson@x.dummyjson.com,+81 965-431-3024,emilys,emilyspass,...,San Francisco,Wisconsin,WI,37657,71.814525,-161.150263,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
1,2,Michael,Williams,,36,male,michael.williams@x.dummyjson.com,+49 258-627-6644,michaelw,michaelwpass,...,Los Angeles,New Hampshire,NH,73442,79.098326,-119.624845,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
2,3,Sophia,Brown,,43,female,sophia.brown@x.dummyjson.com,+81 210-652-2785,sophiab,sophiabpass,...,Dallas,Nevada,NV,88511,20.086743,-34.577107,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
3,4,James,Davis,,46,male,james.davis@x.dummyjson.com,+49 614-958-9364,jamesd,jamesdpass,...,Fort Worth,Pennsylvania,PA,27768,54.911930,-79.498328,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
4,5,Emma,Miller,Johnson,31,female,emma.miller@x.dummyjson.com,+91 759-776-1614,emmaj,emmajpass,...,San Antonio,Idaho,ID,21965,44.346545,-26.944701,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)

In [3]:
df.shape

(100, 52)

In [4]:
df.columns.tolist()

['id',
 'firstName',
 'lastName',
 'maidenName',
 'age',
 'gender',
 'email',
 'phone',
 'username',
 'password',
 'birthDate',
 'image',
 'bloodGroup',
 'height',
 'weight',
 'eyeColor',
 'ip',
 'macAddress',
 'university',
 'ein',
 'ssn',
 'userAgent',
 'role',
 'hair.color',
 'hair.type',
 'address.address',
 'address.city',
 'address.state',
 'address.stateCode',
 'address.postalCode',
 'address.coordinates.lat',
 'address.coordinates.lng',
 'address.country',
 'bank.cardExpire',
 'bank.cardNumber',
 'bank.cardType',
 'bank.currency',
 'bank.iban',
 'company.department',
 'company.name',
 'company.title',
 'company.address.address',
 'company.address.city',
 'company.address.state',
 'company.address.stateCode',
 'company.address.postalCode',
 'company.address.coordinates.lat',
 'company.address.coordinates.lng',
 'company.address.country',
 'crypto.coin',
 'crypto.wallet',
 'crypto.network']

In [5]:
df.dtypes

id                                   int64
firstName                              str
lastName                               str
maidenName                             str
age                                  int64
gender                                 str
email                                  str
phone                                  str
username                               str
password                               str
birthDate                              str
image                                  str
bloodGroup                             str
height                             float64
weight                             float64
eyeColor                               str
ip                                     str
macAddress                             str
university                             str
ein                                    str
ssn                                    str
userAgent                              str
role                                   str
hair.color                             str
hair.type                              str
address.address                        str
address.city                           str
address.state                          str
address.stateCode                      str
address.postalCode                     str
address.coordinates.lat            float64
address.coordinates.lng            float64
address.country                        str
bank.cardExpire                        str
bank.cardNumber                        str
bank.cardType                          str
bank.currency                          str
bank.iban                              str
company.department                     str
company.name                           str
company.title                          str
company.address.address                str
company.address.city                   str
company.address.state                  str
company.address.stateCode              str
company.address.postalCode             str
company.address.coordinates.lat    float64
company.address.coordinates.lng    float64
company.address.country                str
crypto.coin                            str
crypto.wallet                          str
crypto.network                         str
dtype: object

In [6]:
df.isnull().sum().sort_values(ascending=True)

id                                 0
firstName                          0
lastName                           0
maidenName                         0
age                                0
gender                             0
email                              0
phone                              0
username                           0
password                           0
birthDate                          0
image                              0
bloodGroup                         0
height                             0
weight                             0
eyeColor                           0
ip                                 0
macAddress                         0
university                         0
ein                                0
ssn                                0
userAgent                          0
role                               0
hair.color                         0
hair.type                          0
address.address                    0
address.city                       0
address.state                      0
address.stateCode                  0
address.postalCode                 0
address.coordinates.lat            0
address.coordinates.lng            0
address.country                    0
bank.cardExpire                    0
bank.cardNumber                    0
bank.cardType                      0
bank.currency                      0
bank.iban                          0
company.department                 0
company.name                       0
company.title                      0
company.address.address            0
company.address.city               0
company.address.state              0
company.address.stateCode          0
company.address.postalCode         0
company.address.coordinates.lat    0
company.address.coordinates.lng    0
company.address.country            0
crypto.coin                        0
crypto.wallet                      0
crypto.network                     0
dtype: int64

In [7]:
x=df.duplicated().sum()
print(x)

0

In [8]:
df.describe()

,id,age,height,weight,address.coordinates.lat,address.coordinates.lng,company.address.coordinates.lat,company.address.coordinates.lng
count,100.000000,100.000000,100.000000,100.0000,100.000000,100.000000,100.000000,100.000000
mean,50.500000,31.700000,176.392500,75.0431,0.304661,-8.426883,3.300877,-10.039483
std,29.011492,4.132893,13.838342,14.0146,52.833371,105.246649,51.892119,102.017108
min,1.000000,23.000000,150.250000,50.1000,-87.184494,-176.861979,-86.557025,-169.602231
25%,25.750000,28.750000,166.700000,63.0075,-46.076624,-87.475943,-47.014297,-91.900357
50%,50.500000,31.000000,178.320000,75.4600,3.090987,-27.686222,11.113367,-12.890487
75%,75.250000,34.000000,187.617500,87.5175,42.178338,81.048713,45.542705,83.312120
max,100.000000,46.000000,199.620000,98.7700,89.781211,179.922909,89.270633,178.506028

In [9]:
df["gender"].value_counts()

gender
female    52
male      48
Name: count, dtype: int64

In [10]:
df["bloodGroup"].value_counts()

bloodGroup
O-     19
A+     15
AB+    13
AB-    13
B+     12
B-     10
O+     10
A-      8
Name: count, dtype: int64

In [11]:
df["eyeColor"].value_counts()

eyeColor
Brown     18
Hazel     16
Gray      14
Red       12
Blue      12
Green     11
Amber     10
Violet     7
Name: count, dtype: int64

In [12]:
df["role"].value_counts()

role
user         85
moderator    10
admin         5
Name: count, dtype: int64

In [13]:
df["address.country"].value_counts()

address.country
United States    100
Name: count, dtype: int64

In [14]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

In [ ]:
df["maidenName"].value_counts()

In [19]:
df.drop("maidenName", axis=1, inplace=True)

In [21]:
df.tail(5)

,id,firstName,lastName,age,gender,email,phone,username,password,birthDate,image,bloodGroup,height,weight,eyeColor,ip,macAddress,university,ein,ssn,userAgent,role,hair.color,hair.type,address.address,address.city,address.state,address.stateCode,address.postalCode,address.coordinates.lat,address.coordinates.lng,address.country,bank.cardExpire,bank.cardNumber,bank.cardType,bank.currency,bank.iban,company.department,company.name,company.title,company.address.address,company.address.city,company.address.state,company.address.stateCode,company.address.postalCode,company.address.coordinates.lat,company.address.coordinates.lng,company.address.country,crypto.coin,crypto.wallet,crypto.network
95,96,Aurora,Lawson,27,female,aurora.lawson@x.dummyjson.com,+92 802-452-4192,auroral,auroralpass,1998-6-16,https://dummyjson.com/icon/auroral/128,O+,174.28,88.18,Violet,161.244.58.227,34:95:bd:59:f4:39,Boston University,477-337,191-532-292,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:9...,user,Green,Wavy,1140 Adams Street,Dallas,Minnesota,MN,29004,83.417744,-7.933044,United States,07/29,5480171454066942,Mastercard,GBP,GB36C9TE2MIXX12X8IJMLG,Product Management,Hudson - Marquardt,Chief Information Officer,164 Fifth Street,Indianapolis,New York,NY,27958,89.270633,-72.618747,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
96,97,Oscar,Powers,34,male,oscar.powers@x.dummyjson.com,+61 929-572-1408,oscarp,oscarppass,1991-9-7,https://dummyjson.com/icon/oscarp/128,O+,169.03,62.55,Violet,216.204.186.222,79:d9:1b:19:e2:73,University of Virginia,325-379,856-795-126,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,user,Green,Wavy,1948 Jefferson Street,Charlotte,Vermont,VT,12263,52.294653,-70.699360,United States,11/27,6011597179762975,Discover,USD,DE16654874987771550206,Legal,Luettgen and Sons,Support Specialist,1127 Oak Street,Chicago,Alabama,AL,37894,28.080301,-6.017825,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
97,98,Clara,Berry,31,female,clara.berry@x.dummyjson.com,+1 390-831-5172,clarab,clarabpass,1994-2-13,https://dummyjson.com/icon/clarab/128,O-,151.55,90.27,Red,144.153.81.107,30:fa:b2:ca:17:91,Boston College,246-495,625-638-955,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,user,Blue,Wavy,1577 Jefferson Street,Seattle,Montana,MT,41818,88.607515,92.692781,United States,10/29,348500223799446,American Express,JPY,DE94679076797491453575,Training,Mayer - Smitham,Accountant,767 Adams Street,Phoenix,Washington,WA,13037,76.372465,24.919329,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
98,99,Gavin,Stanley,33,male,gavin.stanley@x.dummyjson.com,+44 466-358-6026,gavins,gavinspass,1992-3-17,https://dummyjson.com/icon/gavins/128,O-,173.37,92.17,Amber,189.110.169.3,34:32:b0:9:28:0,University of California--Irvine,780-590,321-561-524,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,user,Black,Straight,1898 Second Street,Houston,Mississippi,MS,85234,70.915423,-30.195987,United States,03/27,3581201445671725,JCB,CAD,DE01439050186894663094,Marketing,"Strosin, Anderson and Baumbach",Support Specialist,903 First Street,San Diego,Iowa,IA,87476,-47.007951,86.840506,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)
99,100,Lila,Hudson,28,female,lila.hudson@x.dummyjson.com,+91 697-236-1544,lilah,lilahpass,1997-9-1,https://dummyjson.com/icon/lilah/128,AB+,190.10,70.03,Gray,96.35.42.117,96:21:23:2c:f:d5,University of Notre Dame,306-959,297-645-204,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,user,Blonde,Wavy,262 Ninth Street,Chicago,Nevada,NV,17472,-68.233207,-67.042550,United States,12/29,3573611722474066,JCB,EUR,DE23981874800457879322,Legal,"Hartmann, Hilpert and Kulas",Sales Manager,1825 Oak Street,New York,Kansas,KS,71983,50.551530,39.433391,United States,Bitcoin,0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a,Ethereum (ERC20)

In [22]:
df.drop(["company.address.stateCode","crypto.wallet","company.address.postalCode","bank.iban","macAddress","userAgent","address.postalCode","address.stateCode"], axis=1, inplace=True)

In [25]:
df.sample(10)

,id,firstName,lastName,age,gender,email,phone,username,password,birthDate,image,bloodGroup,height,weight,eyeColor,ip,university,ein,ssn,role,hair.color,hair.type,address.address,address.city,address.state,address.coordinates.lat,address.coordinates.lng,address.country,bank.cardExpire,bank.cardNumber,bank.cardType,bank.currency,company.department,company.name,company.title,company.address.address,company.address.city,company.address.state,company.address.coordinates.lat,company.address.coordinates.lng,company.address.country,crypto.coin,crypto.network
53,54,Ava,Harrison,29,female,ava.harrison@x.dummyjson.com,+44 926-778-4653,avah,avahpass,1996-4-22,https://dummyjson.com/icon/avah/128,O-,155.72,93.47,Hazel,225.40.138.177,Harvard University,145-780,621-536-422,user,Brown,Curly,1094 Adams Street,San Antonio,Vermont,-84.032892,-46.255902,United States,01/27,3694482369735209,Diners Club International,AUD,Engineering,Blanda - Jacobson,Legal Counsel,1374 Cedar Street,Philadelphia,Delaware,-56.564069,-134.428790,United States,Bitcoin,Ethereum (ERC20)
23,24,Mateo,Nguyen,31,male,mateo.nguyen@x.dummyjson.com,+1 341-597-6694,mateon,mateonpass,1994-6-2,https://dummyjson.com/icon/mateon/128,O+,174.29,59.98,Red,192.57.144.7,Columbia University,229-249,416-877-230,user,Purple,Wavy,1578 Fourth Street,Columbus,Missouri,-32.828675,-82.557354,United States,12/29,4021840414995098,Visa,CAD,Accounting,Spinka LLC,Business Analyst,1967 Jefferson Street,Dallas,Louisiana,75.982676,164.459743,United States,Bitcoin,Ethereum (ERC20)
13,14,Charlotte,Lopez,37,female,charlotte.lopez@x.dummyjson.com,+44 373-953-5028,charlottem,charlottempass,1988-6-8,https://dummyjson.com/icon/charlottem/128,AB-,178.92,82.46,Brown,119.103.95.60,Northeastern University,364-782,255-491-479,moderator,Gray,Kinky,208 Second Street,Columbus,Ohio,-44.443762,-151.420561,United States,12/27,3634388457177035,Diners Club International,PKR,Accounting,Zulauf and Sons,Chief Executive Officer,569 Jefferson Street,Los Angeles,Montana,-18.371256,22.566258,United States,Bitcoin,Ethereum (ERC20)
59,60,Lillian,Simmons,33,female,lillian.simmons@x.dummyjson.com,+61 857-625-2029,lillians,lillianspass,1992-3-9,https://dummyjson.com/icon/lillians/128,A+,173.72,87.33,Gray,161.193.124.63,Boston University,504-909,593-729-652,user,Black,Kinky,1577 Seventh Street,Phoenix,Minnesota,-78.054184,-159.412033,United States,08/28,4194199742529819,Visa,AUD,Business Development,"Will, Stamm and Zieme",Legal Counsel,1624 Maple Street,Denver,Montana,-17.662779,165.102747,United States,Bitcoin,Ethereum (ERC20)
97,98,Clara,Berry,31,female,clara.berry@x.dummyjson.com,+1 390-831-5172,clarab,clarabpass,1994-2-13,https://dummyjson.com/icon/clarab/128,O-,151.55,90.27,Red,144.153.81.107,Boston College,246-495,625-638-955,user,Blue,Wavy,1577 Jefferson Street,Seattle,Montana,88.607515,92.692781,United States,10/29,348500223799446,American Express,JPY,Training,Mayer - Smitham,Accountant,767 Adams Street,Phoenix,Washington,76.372465,24.919329,United States,Bitcoin,Ethereum (ERC20)
75,76,Madeline,Simpson,27,female,madeline.simpson@x.dummyjson.com,+44 371-964-4017,madelines,madelinespass,1998-12-1,https://dummyjson.com/icon/madelines/128,AB+,181.51,67.70,Brown,29.230.204.12,University of Rochester,795-274,220-119-957,user,Blonde,Straight,1466 Oak Street,Los Angeles,New Jersey,-61.252684,-159.370289,United States,10/28,5598889672042796,Mastercard,EUR,Product Management,King - Muller,Web Developer,1090 Fifth Street,Jacksonville,Utah,12.345847,90.721037,United States,Bitcoin,Ethereum (ERC20)
25,26,Evelyn,Gonzalez,36,female,evelyn.gonzalez@x.dummyjson.com,+61 708-508-4638,evelyng,evelyngpass,1989-2-5,https://dummyjson.com/icon/evelyng/128,O+,168.94,58.47,Red,42.52.74.232,Washington University in St. Louis,569-275,487-680-127,user,Black,Wavy,1065 Lincoln Street,Dallas,Maine,67.768359,71.268643,United States,08/28,6011735364912274,Discover,CAD,Accounting,"Tromp, Gaylord and Weber",Project Manager,584 Ninth Street,Jacksonville,Wisconsin,26.014021,40.572436,United States,Bitcoin,Ethereum (ERC20)
90,91,Levi,Hicks,30,male,levi.hicks@x.dummyjson.com,+92 931-753-3850,levih,levihpass,1995-5-19,https://dummyjson.com/icon/levih/128,A-,199.06,95.68,Red,235.155.45.205,Ohio State University,858-254,510-891-185,user,Blue,Curly,1836 Pine Street,Phoenix,West Virginia,43.752994,-60.845798,United States,08/27,6011037232328647,Discover,CAD,Product Management,Quitzon LLC,Software Architect,388 Elm Street,Charlotte,Vermont,18.856177,36.280746,United States,Bitcoin,Ethereum (ERC20)
2,3,Sophia,Brown,43,female,sophia.brown@x.dummyjson.com,+81 210-652-2785,sophiab,sophiabpass,1982-11-6,https://dummyjson.com/icon/sophiab/128,O-,177.72,52.60,Hazel,214.225.51.195,Pepperdine University,963-113,638-461-822,admin,White,Wavy,1642 Ninth Street,Washington,Alabama,45.289366,46.832664,United States,10/27,6011212053392887,Discover,EUR,Research and Development,Schiller - Zieme,Accountant,1896 Washington Street,Dallas,Nevada,20.086743,-34.577107,United States,Bitcoin,Ethereum (ERC20)
95,96,Aurora,Lawson,27,female,aurora.lawson@x.dummyjson.com,+92 802-452-4192,auroral,auroralpass,1998-6-16,https://dummyjson.com/icon/auroral/128,O+,174.28,88.18,Violet,161.244.58.227,Boston University,477-337,191-532-292,user,Green,Wavy,1140 Adams Street,Dallas,Minnesota,83.417744,-7.933044,United States,07/29,5480171454066942,Mastercard,GBP,Product Management,Hudson - Marquardt,Chief Information Officer,164 Fifth Street,Indianapolis,New York,89.270633,-72.618747,United States,Bitcoin,Ethereum (ERC20)

In [16]:

df[["age", "height", "weight"]].isnull().sum()

age       0
height    0
weight    0
dtype: int64

In [26]:
df["age"].fillna(df["age"].median(), inplace=True)
df["height"].fillna(df["height"].median(), inplace=True)
df["weight"].fillna(df["weight"].median(), inplace=True)

C:\Users\eLROWAD\AppData\Local\Temp\ipykernel_2120\187645330.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["age"].fillna(df["age"].median(), inplace=True)
C:\Users\eLROWAD\AppData\Local\Temp\ipykernel_2120\187645330.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["height"].fillna(df["height"].median(), inplace=True)
C:\Users\eLROWAD\AppData\Local\Temp\ipykernel_2120\187645330.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["weight"].fillna(df["weight"].median(), inplace=True)

0     63.16
1     76.32
2     52.60
3     62.10
4     63.62
      ...
95    88.18
96    62.55
97    90.27
98    92.17
99    70.03
Name: weight, Length: 100, dtype: float64

In [ ]:
!pip install matplotlib seaborn

In [27]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

ModuleNotFoundError: No module named 'matplotlib'